name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cd ./cachew && cargo build --verbose
    - name: Run tests
      run: cd ./cachew && cargo test --verbose
    - name: Check coverage
      run: cargo install cargo-tarpaulin && cargo tarpaulin --no-count --skip-clean --out Xml && bash <(curl -s https://codecov.io/bash)