name: CI cli-client

on:
  push:
    paths: [ cli-client/** ]
    branches: [ "main" ]
  pull_request:
    paths: [ cli-client/** ]
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cd ./cli-client && cargo build --verbose
    - name: Run tests
      run: cd ./cli-client && cargo test --verbose